esphome:
  name: office-door

esp8266:
  board: d1_mini
  
logger:

api:
  password: "123456"

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


cover:
  - platform: endstop
    name: "Office Door"
    id: officedoor
    open_action:
      - switch.turn_on: bedliftup1
    open_duration: 6s
    open_endstop: windowstopbottom

    close_action:
      - switch.turn_on: bedliftup2
    close_duration: 6s
    close_endstop: windowstoptop

    stop_action:
      - switch.turn_off: bedliftup2
      - switch.turn_off: bedliftup1     
    max_duration: 7s
    
binary_sensor:
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
    id: windowstopbottom
    name: Office Door Close Stop
    filters:
      - invert:
      - delayed_on: 100ms
      - delayed_off: 100ms     
    on_state:
      then:
       - cover.close: officedoor
      
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    id: windowstoptop
    name: Office Door Open Stop
    filters:
      - invert:
      - delayed_on: 100ms
      - delayed_off: 100ms         
switch:
  - platform: gpio
    pin: D3
    inverted: yes    
    id: bedliftup1
    interlock: [bedliftup2]
    interlock_wait_time: 500ms
  - platform: gpio
    pin: D4
    inverted: yes    
    id: bedliftup2   
    interlock: [bedliftup1]
    interlock_wait_time: 500ms    